/* Run after npm run build:web. Browser: npx playwright install chromium. */
const { chromium }=require('playwright');
const { spawn }=require('node:child_process');
const fs=require('node:fs');
const assert=require('node:assert/strict');
const path=require('node:path');
(async()=>{
  fs.mkdirSync('qa',{recursive:true});
  const server=spawn(process.execPath,['scripts/serve.mjs'],{stdio:['ignore','pipe','inherit']});
  await new Promise((resolve,reject)=>{server.stdout.once('data',resolve);server.once('error',reject);});
  const results=[];let browser;const errors=[];
  try{
    browser=await chromium.launch({headless:true,...(process.env.PAYLAK_CHROMIUM_PATH?{executablePath:process.env.PAYLAK_CHROMIUM_PATH,args:['--no-sandbox','--disable-dev-shm-usage','--no-zygote','--single-process']}:{})});
    const page=await browser.newPage({viewport:{width:390,height:844},deviceScaleFactor:1});
    page.on('pageerror',e=>errors.push(e.message));
    const start=async()=>{await page.goto('http://127.0.0.1:4174/');await page.getByRole('button',{name:'Send',exact:true}).waitFor();};
    const check=async(name,fn)=>{try{await fn();results.push({name,status:'PASS'});console.log('PASS',name);}catch(e){results.push({name,status:'FAIL',error:e.message});console.error('FAIL',name,e.message);await page.screenshot({path:`qa/failure-${results.length}.png`});throw e;}};
    const click=async(name)=>page.getByRole('button',{name,exact:true}).click();
    const has=async(text)=>assert.ok((await page.locator('body').innerText()).includes(text),`Expected ${text}`);
    await check('Home renders separate wallet and card balances',async()=>{await start();await has('$2,450.00');await has('$1,080.00');await page.screenshot({path:'qa/home-dark.png'});});
    await check('All five primary tabs navigate',async()=>{for(const name of ['Payments','Cards','Cash','Services','Home']){await page.getByRole('tab',{name,exact:true}).click();await page.getByRole('tab',{name,exact:true}).waitFor();}});
    await check('Send validates empty and excessive amounts',async()=>{await click('Send');await click('Review transfer');await has('Enter a valid amount');await page.getByLabel('Amount in USD',{exact:true}).fill('99999');await click('Review transfer');await has('Not enough available');});
    await check('Send reviews, commits and updates wallet',async()=>{await page.getByLabel('Amount in USD',{exact:true}).fill('150');await click('Review transfer');await has('$2,300.00');await page.screenshot({path:'qa/send-review.png'});await click('Confirm demo payment');await has('Demo completed');await page.screenshot({path:'qa/receipt.png'});await click('Back to Home');await has('$2,300.00');});
    await check('Payment contact shortcut preserves selected recipient',async()=>{await start();await page.getByRole('tab',{name:'Payments',exact:true}).click();await page.getByRole('button',{name:/Karim/}).click();await page.getByLabel('Amount in USD',{exact:true}).fill('5');await click('Review transfer');await has('To Karim Nassar');});
    await check('Cash acceptance holds funds and cancel releases once',async()=>{await start();await click('Get cash');await page.screenshot({path:'qa/cash.png'});await click('Request a cash reservation');await page.getByLabel('Cash amount in USD').fill('300');await click('Review cash request');await has('$1.50');await click('Simulate agent acceptance');await has('Cash reserved');await click('Cancel reservation & release hold');await has('Reservation cancelled');await click('Back to Home');await has('$2,450.00');});
    await check('Card freeze and load affect distinct funds',async()=>{await start();await page.getByRole('tab',{name:'Cards',exact:true}).click();await page.screenshot({path:'qa/cards-dark.png'});await click('Freeze');await has('Unfreeze');await click('Unfreeze');await click('Add card funds');await page.getByLabel('Amount in USD',{exact:true}).fill('100');await click('Review transfer');await click('Confirm demo payment');await click('Back to Home');await has('$2,350.00');await has('$1,180.00');});
    await check('Card personal limit rejects below-spent cap',async()=>{await page.getByRole('tab',{name:'Cards',exact:true}).click();await click('Limits');await page.getByLabel('Monthly limit in USD').fill('100');await click('Save limit');await has('Choose a demo limit');await page.getByLabel('Monthly limit in USD').fill('2000');await click('Save limit');await has('Limit updated');});
    await check('Activity has useful no-results state',async()=>{await start();await page.getByRole('button',{name:'See all',exact:true}).click();await page.getByLabel('Search activity').fill('ZZZNONEXISTENT');await has('No transactions match');});
    await check('Top-up validates destination and completes sample order',async()=>{await start();await page.getByRole('tab',{name:'Services',exact:true}).click();await page.getByRole('button',{name:/Mobile top-ups/}).click();await click('Review top-up');await has('valid 8-digit');await page.getByLabel('Lebanese mobile number').fill('03 123 456');await page.getByLabel('Top-up amount in USD').fill('10');await click('Review top-up');await click('Confirm demo payment');await has('Demo completed');});
    await check('eSIM sample purchase is explicitly non-provisioning',async()=>{await start();await page.getByRole('tab',{name:'Services',exact:true}).click();await click('Explore eSIMs');await page.screenshot({path:'qa/esim.png'});await page.getByRole('button',{name:'Preview sample plan · $12.00',exact:true}).click();await has('no activation');});
    await check('USDT is disabled and exposes no deposit address',async()=>{await start();await page.getByRole('tab',{name:'Services',exact:true}).click();await page.getByRole('button',{name:'USDT, Service availability',exact:true}).click();await has('Not activated');await has('No deposit address');});
    await check('Support case is local and honestly labelled',async()=>{await start();await click('Help');await page.getByLabel('How can we help?').fill('Please check my sample transfer.');await click('Create sample support case');await has('It has not been sent');});
    await check('Offline scenario prevents a quote',async()=>{await start();await click('Profile');await click('offline');await click('Back');await click('Send');await page.getByLabel('Amount in USD',{exact:true}).fill('10');await click('Review transfer');await has('You’re offline');});
    await check('Declined scenario never debits the wallet',async()=>{await start();await click('Profile');await click('declined');await click('Back');await click('Send');await page.getByLabel('Amount in USD',{exact:true}).fill('10');await click('Review transfer');await click('Confirm demo payment');await has('Nothing was debited');});
    await check('Pending scenario retains the operation reference',async()=>{await start();await click('Profile');await click('pending');await click('Back');await click('Send');await page.getByLabel('Amount in USD',{exact:true}).fill('10');await click('Review transfer');await click('Confirm demo payment');await has('Waiting for confirmation');await has('PL-DEMO-');});
    await check('Arabic amount entry and mirrored navigation',async()=>{await start();await page.getByRole('button',{name:'Switch to Arabic'}).click();await has('رصيد محفظة USD المتاح');await page.screenshot({path:'qa/home-arabic.png'});await click('إرسال');await page.getByLabel('المبلغ بالدولار',{exact:true}).fill('١٢٫٣٤');await click('راجع التحويل');await has('$12.34');});
    await check('Light appearance remains legible',async()=>{await start();await click('Profile');await page.getByRole('switch',{name:'Dark appearance'}).click();await click('Back');await page.screenshot({path:'qa/home-light.png'});await has('$2,450.00');});
    await check('Narrow phone has no horizontal overflow',async()=>{await page.setViewportSize({width:320,height:740});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));await page.screenshot({path:'qa/home-320.png'});});
    await check('All secondary route entry points render without crashing',async()=>{for(const name of ['request','add','load','activity','profile','support','onboarding','reserve','topup','esim','bills','usdt','pockets','business','international','limits','notifications','security']){await page.goto(`http://127.0.0.1:4174/screen/${name}`);await page.getByText('INTERACTIVE DEMO · NO REAL MONEY',{exact:true}).waitFor();assert.ok((await page.locator('body').innerText()).length>80);}});
    await check('Website desktop and mobile, Arabic toggle and FAQ',async()=>{await page.setViewportSize({width:1440,height:1000});await page.goto('http://127.0.0.1:4174/website/');await page.screenshot({path:'qa/website-desktop.png',fullPage:true});await page.screenshot({path:'qa/website-hero.png'});await page.getByText('Can I open a real account?',{exact:true}).click();await has('Not yet.');await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));await page.screenshot({path:'qa/website-mobile.png',fullPage:true});await page.getByRole('button',{name:'Switch language'}).click();assert.equal(await page.locator('html').getAttribute('dir'),'rtl');await page.screenshot({path:'qa/website-arabic.png',fullPage:true});});
    await check('No browser runtime errors',async()=>assert.deepEqual(errors,[]));
  }catch(e){process.exitCode=1;}finally{fs.writeFileSync('qa/browser-results.json',JSON.stringify({date:new Date().toISOString(),results,runtimeErrors:errors},null,2));if(browser)await browser.close();server.kill();}
})();
